=== Olderrest/Simulation/simulation-schema.xsd
<?xml version="1.1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="simulation">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="years">
                    <xs:complexType>
                        <xs:attribute name="quantity" type="xs:unsignedInt"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="months">
                    <xs:complexType>
                        <xs:attribute name="quantity" type="xs:unsignedInt"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="days">
                    <xs:complexType>
                        <xs:attribute name="quantity" type="xs:unsignedInt"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="routes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="route" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="route">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="routeType"/>
                <xs:element name="stops">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="stop" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="buses">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="bus" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="interval" type="xs:unsignedInt" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="stop">
        <xs:complexType>
            <xs:attribute name="time" type="xs:unsignedInt"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="bus">
        <xs:complexType>
            <xs:attribute name="size" type="xs:unsignedInt" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="routeType">
        <xs:complexType>
           <xs:attribute name="type" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Olderrest/Simulation/simulation.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../resources/simulation-schema.xsd">
    <years quantity="0"/>
    <months quantity="3"/>
    <days quantity="0"/>
    <routes>
        <route interval="5">
            <routeType type="straight"/>
            <stops>
                <stop time="5"/>
                <stop time="8"/>
                <stop time="5"/>
                <stop time="7"/>
                <stop time="10"/>
                <stop time="10"/>
                <stop time="10"/>
            </stops>
            <buses>
                <bus size="25"/>
                <bus size="30"/>
                <bus size="25"/>
                <bus size="30"/>
            </buses>
        </route>
        <route interval="5">
            <routeType type="circular"/>
            <stops>
                <stop time="3"/>
                <stop time="6"/>
                <stop time="9"/>
                <stop time="4"/>
                <stop time="7"/>
            </stops>
            <buses>
                <bus size="25"/>
                <bus size="35"/>
            </buses>
        </route>
        <route interval="7">
            <routeType type="circular"/>
            <stops>
                <stop time="3"/>
                <stop time="6"/>
                <stop time="9"/>
                <stop time="7"/>
                <stop time="7"/>
                <stop time="10"/>
            </stops>
            <buses>
                <bus size="30"/>
                <bus size="20"/>
                <bus size="35"/>
            </buses>
        </route>
        <route interval="10">
            <routeType type="circular"/>
            <stops>
                <stop time="7"/>
                <stop time="5"/>
                <stop time="9"/>
                <stop time="11"/>
                <stop time="7"/>
                <stop time="8"/>
            </stops>
            <buses>
                <bus size="20"/>
                <bus size="30"/>
                <bus size="25"/>
            </buses>
        </route>
        <route interval="5">
            <routeType type="straight"/>
            <stops>
                <stop time="5"/>
                <stop time="8"/>
                <stop time="5"/>
                <stop time="7"/>
                <stop time="10"/>
                <stop time="10"/>
                <stop time="10"/>
            </stops>
            <buses>
                <bus size="25"/>
                <bus size="30"/>
                <bus size="25"/>
                <bus size="30"/>
            </buses>
        </route>
        <route interval="5">
            <routeType type="circular"/>
            <stops>
                <stop time="3"/>
                <stop time="6"/>
                <stop time="9"/>
                <stop time="4"/>
                <stop time="7"/>
            </stops>
            <buses>
                <bus size="25"/>
                <bus size="35"/>
            </buses>
        </route>
        <route interval="7">
            <routeType type="circular"/>
            <stops>
                <stop time="3"/>
                <stop time="6"/>
                <stop time="9"/>
                <stop time="7"/>
                <stop time="7"/>
                <stop time="10"/>
            </stops>
            <buses>
                <bus size="30"/>
                <bus size="20"/>
                <bus size="35"/>
            </buses>
        </route>
        <route interval="10">
            <routeType type="circular"/>
            <stops>
                <stop time="7"/>
                <stop time="5"/>
                <stop time="9"/>
                <stop time="11"/>
                <stop time="7"/>
                <stop time="8"/>
            </stops>
            <buses>
                <bus size="20"/>
                <bus size="30"/>
                <bus size="25"/>
            </buses>
        </route>
        <route interval="5">
            <routeType type="straight"/>
            <stops>
                <stop time="5"/>
                <stop time="8"/>
                <stop time="5"/>
                <stop time="7"/>
                <stop time="10"/>
                <stop time="10"/>
                <stop time="10"/>
            </stops>
            <buses>
                <bus size="25"/>
                <bus size="30"/>
                <bus size="25"/>
                <bus size="30"/>
            </buses>
        </route>
        <route interval="5">
            <routeType type="circular"/>
            <stops>
                <stop time="3"/>
                <stop time="6"/>
                <stop time="9"/>
                <stop time="4"/>
                <stop time="7"/>
            </stops>
            <buses>
                <bus size="25"/>
                <bus size="35"/>
            </buses>
        </route>
        <route interval="7">
            <routeType type="circular"/>
            <stops>
                <stop time="3"/>
                <stop time="6"/>
                <stop time="9"/>
                <stop time="7"/>
                <stop time="7"/>
                <stop time="10"/>
            </stops>
            <buses>
                <bus size="30"/>
                <bus size="20"/>
                <bus size="35"/>
            </buses>
        </route>
        <route interval="10">
            <routeType type="circular"/>
            <stops>
                <stop time="7"/>
                <stop time="5"/>
                <stop time="9"/>
                <stop time="11"/>
                <stop time="7"/>
                <stop time="8"/>
            </stops>
            <buses>
                <bus size="20"/>
                <bus size="30"/>
                <bus size="25"/>
            </buses>
        </route>
        <route interval="5">
            <routeType type="straight"/>
            <stops>
                <stop time="5"/>
                <stop time="8"/>
                <stop time="5"/>
                <stop time="7"/>
                <stop time="10"/>
                <stop time="10"/>
                <stop time="10"/>
            </stops>
            <buses>
                <bus size="25"/>
                <bus size="30"/>
                <bus size="25"/>
                <bus size="30"/>
            </buses>
        </route>
        <route interval="5">
            <routeType type="circular"/>
            <stops>
                <stop time="3"/>
                <stop time="6"/>
                <stop time="9"/>
                <stop time="4"/>
                <stop time="7"/>
            </stops>
            <buses>
                <bus size="25"/>
                <bus size="35"/>
            </buses>
        </route>
        <route interval="7">
            <routeType type="circular"/>
            <stops>
                <stop time="3"/>
                <stop time="6"/>
                <stop time="9"/>
                <stop time="7"/>
                <stop time="7"/>
                <stop time="10"/>
            </stops>
            <buses>
                <bus size="30"/>
                <bus size="20"/>
                <bus size="35"/>
            </buses>
        </route>
        <route interval="10">
            <routeType type="circular"/>
            <stops>
                <stop time="7"/>
                <stop time="5"/>
                <stop time="9"/>
                <stop time="11"/>
                <stop time="7"/>
                <stop time="8"/>
            </stops>
            <buses>
                <bus size="20"/>
                <bus size="30"/>
                <bus size="25"/>
            </buses>
        </route>
        <route interval="5">
            <routeType type="straight"/>
            <stops>
                <stop time="5"/>
                <stop time="8"/>
                <stop time="5"/>
                <stop time="7"/>
                <stop time="10"/>
                <stop time="10"/>
                <stop time="10"/>
            </stops>
            <buses>
                <bus size="25"/>
                <bus size="30"/>
                <bus size="25"/>
                <bus size="30"/>
            </buses>
        </route>
        <route interval="5">
            <routeType type="circular"/>
            <stops>
                <stop time="3"/>
                <stop time="6"/>
                <stop time="9"/>
                <stop time="4"/>
                <stop time="7"/>
            </stops>
            <buses>
                <bus size="25"/>
                <bus size="35"/>
            </buses>
        </route>
        <route interval="7">
            <routeType type="circular"/>
            <stops>
                <stop time="3"/>
                <stop time="6"/>
                <stop time="9"/>
                <stop time="7"/>
                <stop time="7"/>
                <stop time="10"/>
            </stops>
            <buses>
                <bus size="30"/>
                <bus size="20"/>
                <bus size="35"/>
            </buses>
        </route>
        <route interval="10">
            <routeType type="circular"/>
            <stops>
                <stop time="7"/>
                <stop time="5"/>
                <stop time="9"/>
                <stop time="11"/>
                <stop time="7"/>
                <stop time="8"/>
            </stops>
            <buses>
                <bus size="20"/>
                <bus size="30"/>
                <bus size="25"/>
            </buses>
        </route>
        <route interval="5">
            <routeType type="straight"/>
            <stops>
                <stop time="5"/>
                <stop time="8"/>
                <stop time="5"/>
                <stop time="7"/>
                <stop time="10"/>
                <stop time="10"/>
                <stop time="10"/>
            </stops>
            <buses>
